env: test23
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-wait: 1000
        min-idle: 1
        max-idle: 10
        max-active: 1000
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
