env: test
server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.199.153.106:3306/cloud?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 139.199.153.106
    port: 5672
    username: admin
    password: admin
  redis:
    database: 0
    host: 139.199.153.106
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-wait: 1000
        min-idle: 1
        max-idle: 10
        max-active: 1000
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
