env: test
server:
  port: 8083
spring:
  application:
    name: zuul
zuul:
  routes:
    myZuul:
      service-id: product
      path: /kapok-a/**
      sensitiveHeaders: 
  ignored-patterns:
    - /**/product/listForOrder.do
